services:
  db-e11evenn:
    container_name: e11evenn-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: e11evenn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de inicialización del SQL

  app:
    container_name: e11evenn-app
    build: .
    depends_on:
      - db-e11evenn
    ports:
      - "8000:8000"

  web:
    container_name: e11evenn-nginx
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data: