services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: miusuario
      POSTGRES_PASSWORD: mipassword
      POSTGRES_DB: midb
    ports:
      - "5432:5432"

  web:
    image: python:3.9-slim
    volumes:
      - ./app:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
